dhis2/dhis2-utils

resources/sql/add-weeks-bimonths-this-year-to-relativeperiods.sql
Closes EyeSeeTea/dhis2/issues/15
=> add migration for weeksthisyear/bimonthsthisyear

resources/sql/check_program_rule_variable_name.sql
=> feat: [DHIS2-10956] - Sql script to check if program rule variable names contains forbidden keywords

tools/dhis2-package-exporter/package_exporter.py
=> New features and bug fixes

tools/dhis2-package-exporter/package_exporter.py
Check indicators assigned to a dataSet and verify if they are already included in the package, i.e. they are included in an indicatorGroup whose code is prefixed accordingly
=> Stratosilva indicators in data set

tools/dhis2-package-exporter/package_exporter.py
To be able to export a GEN package
https://docs.google.com/document/d/1yhqxGL67Cl6DsjSNbJ7gUOWBoBnr87fPPQz0CRKZuxs
=> Stratosilva gen package feature

tools/dhis2-package-exporter/package_exporter.py
Finally clean up the script: renaming variables, deleting old code...
=> Stratosilva cleanup script

tools/dhis2-package-exporter/package_exporter.py
Remove deprecated mandatory parameters, health area and intervention
Move -pf optional to mandatory, second parameter
Create third mandatory parameter for package code
=> Change in parametrization of script

tools/dhis2-audit-data-extractor/COPYING, tools/dhis2-audit-data-extractor/README.md, tools/dhis2-audit-data-extractor/extract_audit.py
This MR points to version 1.0 of the script with lots of improvements.
Please refer to README for more information.
=> feat: audit data extractor version 1.0

tools/dhis2-package-exporter/package_exporter.py
Add programSections as new metadata type to package when packaging TRK or EVT package types
=> Added programSections

tools/dhis2-audit-data-extractor/COPYING, tools/dhis2-audit-data-extractor/README.md, tools/dhis2-audit-data-extractor/extract_audit.py
Releasing version 1.1 with code optimization and new features.
=> Audit data extractor v1.1

resources/sql/clean_up_option_sort_order.sql
https://jira.dhis2.org/browse/DHIS2-12828
=> feat: script for cleaning up option sort_order

resources/sql/clean_up_option_sort_order.sql
Add a null check for optionvalue.sort_order in case user update sort_order = null directly to DB
=> fix: add check for null sort_order

tools/dhis2-package-exporter/package_exporter.py
Sorry, this commit actually contains two things
Removing charts and reportTables support which were discontinued in 2.34
Add the support to eventVisualisations (starting from 2.38). I realized that by introducing 
if any(version in api_source.version for version in ['2.36', '2.37']):
We are not supporting 2.34 and 2.35 which probably is correct.
Another thing I added is getting the attribute UIDs (TEAs) used in data dimension in eventVisualisations and comparing those UIDs to the UIDs of the TEAs already fetched for the package, to make sure nothing is missing
=> Add support for eventVisualisations

tools/dhis2-package-exporter/package_exporter.py
Unfortunately we found some fields like formType, XAxisLabel, etc... Which are not included when using :owner
=> Restore fields=* after some fields missing

tools/dhis2-dashboardchecker/dashboard_checker.py
'last10Years': 'LAST_10_YEARS',
'last10FinancialYears': 'LAST_10_FINANCIAL_YEARS'
=> Add new relative periods

tools/dhis2-package-exporter/package_exporter.py
The user role is Package User Role, same in tracker_dev and dev
=> Export User Role for user Package Admin

tools/dhis2-metadatapackagediff/metadata_package_diff.py
The script now works with files in Google Spreadsheets, rather than exporting a csv
Therefore, it needs a spreadsheet title passed as third parameter to be able to create or update a spreadsheet
It will also add the conditional formatting (green for created, blue for updated, red for deleted)
Other changes:
Create worksheets/tabs for each metadata type
Make sure created metadata comes first, then updated, then deleted at the end
=> Major changes to metadata_package_diff.py

tools/dhis2-metadatapackagediff/metadata_package_diff.py
Temporary fix
Sheets API has per-minute quotas, and they're refilled every minute. For example, there's a read request limit of 300 per minute per project. If your app sends 350 requests in one minute, the additional 50 requests exceed the quota and generates a 429: Too many requests HTTP status code response. If this happens, you should use an exponential backoff algorithm. After 1 minute, you can execute requests again. Users can submit multiple requests at the same time, as long as they're within the quota limit.
=> Fix for quota limit exceed error

tools/dhis2-package-exporter/package_exporter.py
Make sure the script captures the references to OUG and OUGS used in visualizations
=> Support for OUG in visualizations

tools/dhis2-package-exporter/package_exporter.py
Documentation here:
https://docs.google.com/document/d/1O58yJQr0GkU9ZZ_FbuxWRzEHYlDTV-6AFjMQw-UJoGM
=> Enforcing and validating sharing

tools/dhis2-dummydataagg/README.md, tools/dhis2-dummydataagg/create_data.py
dummy data OU selected based on OU group memberships. updated readme too.
=> add option for selecting OU groups

tools/dhis2-dummydatatracker/create_TEIs.py
- User can specify OUG{UID} in distribution to create TEI's in the OUs of that OUG only
- A new parameter has been added to make sure the OUs chosen to distribute the TEIs are not repeated
=> Add support for unique OUs and OUGs distribution

tools/dhis2-package-exporter/package_exporter.py
Pandas will deprecate append in the future
=> Replace df.append with df.concat

tools/dhis2-dummydatatracker/create_TEIs.py
Looks like random column is not being used (it should be used if present, to make it backwards compatible)
=> Use random column to decide on randomness of values

tools/dhis2-dummydataagg/create_data.py
Fix to post function to make it compatible with latest DHIS2 version  
Fix to the generation and processing of csv file stored indf_min_max 
Remove some useless code
Improve some checks for numeric values
Bring back possibility to use OUGs in the OU selection parameter
=> Multiple changes

tools/dhis2-metadatapackagediff/metadata_package_diff.py
Also remove sharing.owner from the keys which are not supposed to be diff
=> Do not diff with now owned fields

tools/dhis2-dummydataagg/create_data.py
=> Change append for concat

tools/dhis2-package-exporter/package_exporter.py
dataset_uids variable needs to be updated so in the next iteration sections are correctly filtered and fetched section_uid variable is an old one which has never been used, so it is removed now
=> Sections not being added when package is TRK or EVT

tools/dhis2-dummydatatracker/delete_sh.py
Updating script to delete FF dummy data. Logic should be the same we have FF_syncer repo
=> Updating script to delete FF dummy data

tools/dhis2-metadata_flat_file_syncer/README.md
Adding troubleshooting section to FF Readme file
@stratosilva Manu we experienced this issue in several windows machines. Until we check the upgrade of the libraries inside requirements.txt, good to have a troubleshooting section
=> Adding troubleshooting section to FF readme file

tools/dhis2-metadata_flat_file_syncer/metadata_ff_syncer.py
For multilevel nested properties, the tool was incorrectly trying to convert to iso properties that are of type boolean. Also, I realized that openingDate for OUs will fail to import because Google Spreadsheets changes iso format to something else which is not iso format and therefore we get a 400 error when updating metadata instance for OUs
=> Fix date properties management

tools/dhis2-metadata_flat_file_syncer/metadata_ff_syncer.py
=> Fix metadata_ff_syncer.py

tools/dhis2-metadata_flat_file_syncer/metadata_ff_syncer.py
Previously, set_with_dataframe(..., resize=True) caused inconsistencies when updating a worksheet with fewer rows than its existing row count. The worksheet retained its previous row count, leading to formatting errors due to out-of-bounds operations. This fix ensures that resizing only occurs if the new DataFrame has more rows than the current worksheet, preventing unintended truncation while maintaining correct formatting.
=> Fix worksheet resizing issue when updating with a smaller DataFrame

resources/sql/clean_up_visualization_organisationunit_sort_order.sql
=> added SQL function for fix an issue in visualization organisation unit order
